CREATE TABLE T_ADDRESS
(
    ID             UUID UNIQUE PRIMARY KEY,
    CREATION_TIME  TIMESTAMP NOT NULL,
    CREATED_BY     TEXT      NOT NULL,
    UPDATED_TIME   TIMESTAMP NOT NULL,
    UPDATED_BY     TEXT      NOT NULL,
    ADDRESS_LINE_1 TEXT      NOT NULL,
    ADDRESS_LINE_2 TEXT,
    ADDRESS_LINE_3 TEXT,
    CITY           TEXT      NOT NULL,
    COUNTRY        TEXT,
    ZIP_CODE       TEXT      NOT NULL
);
