CREATE TABLE T_PERSON
(
    ID            UUID UNIQUE PRIMARY KEY,
    CREATION_TIME TIMESTAMP NOT NULL,
    CREATED_BY    TEXT      NOT NULL,
    UPDATED_TIME  TIMESTAMP NOT NULL,
    UPDATED_BY    TEXT      NOT NULL,
    DESCRIPTION   TEXT,
    FIRST_NAME    TEXT,
    SURNAME       TEXT      NOT NULL,
    LOCALE        TEXT,
    ADDRESS_ID    UUID
);

ALTER TABLE T_PERSON
    ADD CONSTRAINT fk_p_address_id FOREIGN KEY (ADDRESS_ID)
        REFERENCES T_ADDRESS (ID);
