CREATE TABLE T_USER
(
    ID             UUID UNIQUE PRIMARY KEY,
    CREATION_TIME  TIMESTAMP NOT NULL,
    CREATED_BY     TEXT      NOT NULL,
    UPDATED_TIME   TIMESTAMP NOT NULL,
    UPDATED_BY     TEXT      NOT NULL,
    EMAIL          TEXT,
    USER_NAME      TEXT      NOT NULL,
    PERSON_ID      UUID      NOT NULL,
    USER_TYPE      TEXT      NOT NULL,
    INACTIVE_SINCE DATE
);

ALTER TABLE T_USER
    ADD CONSTRAINT unique_user_name UNIQUE (USER_NAME);

ALTER TABLE T_USER
    ADD CONSTRAINT fk_u_person_id FOREIGN KEY (PERSON_ID)
        REFERENCES T_PERSON (ID);
