CREATE TABLE T_BLOG
(
    ID            UUID UNIQUE PRIMARY KEY,
    CREATION_TIME TIMESTAMP NOT NULL,
    CREATED_BY    TEXT      NOT NULL,
    UPDATED_TIME  TIMESTAMP NOT NULL,
    UPDATED_BY    TEXT      NOT NULL,
    CREATED       DATE      NOT NULL,
    TITLE         TEXT      NOT NULL,
    USER_ID       UUID      NOT NULL
);

CREATE SEQUENCE T_BLOG_SEQ INCREMENT BY 1 START WITH 100000;

ALTER TABLE T_BLOG
    ADD CONSTRAINT fk_b_user_id FOREIGN KEY (USER_ID)
        REFERENCES T_USER (ID);
