CREATE TABLE T_BLOG_ENTRY
(
    ID            UUID UNIQUE PRIMARY KEY,
    CREATION_TIME TIMESTAMP NOT NULL,
    CREATED_BY    TEXT      NOT NULL,
    UPDATED_TIME  TIMESTAMP NOT NULL,
    UPDATED_BY    TEXT      NOT NULL,
    CREATOR_NAME  TEXT      NOT NULL,
    ENTRY         TEXT      NOT NULL,
    BLOG_ID       UUID      NOT NULL
);

ALTER TABLE T_BLOG_ENTRY
    ADD CONSTRAINT fk_be_blog_id FOREIGN KEY (BLOG_ID)
        REFERENCES T_BLOG (ID);
