CREATE TABLE T_GUEST_BOOK
(
    ID            UUID UNIQUE PRIMARY KEY,
    CREATED_BY    TEXT      NOT NULL,
    CREATION_TIME TIMESTAMP NOT NULL,
    UPDATED_BY    TEXT      NOT NULL,
    UPDATED_TIME  TIMESTAMP NOT NULL,
    TITLE         TEXT      NOT NULL,
    USER_ID       UUID      NOT NULL
);

ALTER TABLE T_GUEST_BOOK
    ADD CONSTRAINT fk_gb_user_id FOREIGN KEY (USER_ID)
        REFERENCES T_USER (ID);
