CREATE TABLE T_GUEST_BOOK
(
  ID            UUID UNIQUE PRIMARY KEY,
  CREATION_TIME TIMESTAMP   NOT NULL,
  CREATED_BY    VARCHAR(50) NOT NULL,
  UPDATED_TIME  TIMESTAMP   NOT NULL,
  UPDATED_BY    VARCHAR(50) NOT NULL,
  TITLE         VARCHAR(50) NOT NULL,
  USER_ID       UUID        NOT NULL
);

ALTER TABLE T_GUEST_BOOK
  ADD CONSTRAINT fk_gb_user_id FOREIGN KEY (USER_ID)
    REFERENCES T_USER (ID);
