CREATE TABLE T_GUEST_BOOK_ENTRY
(
    ID            UUID UNIQUE PRIMARY KEY,
    CREATED_BY    TEXT      NOT NULL,
    CREATION_TIME TIMESTAMP NOT NULL,
    UPDATED_BY    TEXT      NOT NULL,
    UPDATED_TIME  TIMESTAMP NOT NULL,
    GUEST_NAME    TEXT      NOT NULL,
    ENTRY         TEXT      NOT NULL,
    GUEST_BOOK_ID UUID      NOT NULL
);

ALTER TABLE T_GUEST_BOOK_ENTRY
    ADD CONSTRAINT fk_gb_bookentry_id FOREIGN KEY (GUEST_BOOK_ID)
        REFERENCES T_GUEST_BOOK (ID);
