name: continious integration on features
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - name: debug
        run: env
      - name: cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: verify that maven artifact has no dependencies which is of type SNAPSHOT
        uses: jactor-rises/actions/verify-mvn-dependencies@master
      - name: release maven artifact
        uses: jactor-rises/actions/release-mvn-artifact@feature-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build & test with maven
        run: |
          mvn -B install
