name: continious integration on features
on:
  push:
    branches:
      - '**'
      - '!master'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - name: debug
        run: env
      - name: cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: verify that maven artifact has no dependencies which is of type SNAPSHOT
        uses: jactor-rises/actions/verify-mvn-dependencies@master
      - name: build & test with maven
        run: mvn -B install
      - name: prepare maven artifact for release
        uses: jactor-rises/actions/prepare-mvn-release@master
        env:
          TAG_FILE_NAME: .tag-artifact
      - id: commit
        name: commit new version
        uses: zwaldowski/git-commit-action@v1
      - run: echo "${{ steps.commit.outputs.sha }}"