name: continious integration on master
on:
  push:
    branches:
      - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: init
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-java@v1
        with:
          java-version: '13'
      - name: debug
        run: env
      - name: cache maven dependencies
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: verify that no dependencies is of type SNAPSHOT
        uses: jactor-rises/actions/verify-dependencies@master
      - name: build & test with maven
        run: |
          mvn -B install
      - name: prepare maven artifact for release
        uses: jactor-rises/actions/prepare-mvn-release@master
      - name: Run Maven release
        run: ./release.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: commit new version
        uses: EndBug/add-and-commit@v2.1.0
        with:
          author_name: Tor Egil Jacobsen
          author_email: tor.egil.jacobsen@gmail.com
          message: "Bumped to new version"
          path: "."
          pattern: "pom.xml"
          force: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
