name: build run docker
on:
  push:
    branches-ignore:
      - main
    paths:
      - 'persistence/**'

jobs:
  build-docker-run:
    runs-on: ubuntu-latest
    name: build actions with ncc
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - run: npm i -g @zeit/ncc
      - name: Install run-docker
        uses: jactor-rises/actions/node-build-action@v2-node-build-action
        with:
          artifact_folder: jactor-persistence/persistence/run-docker
      - name: Generate timestamp
        id: now
        run: echo ::set-output name=timestamp::$(date +"%Y-%m-%d:%T")
      - uses: jactor-rises/actions/git-commit@v2-git-commit
        with:
          commit_message: "node-build-action@${{ steps.now.outputs.timestamp }}"
          pattern: persistence/run-docker/.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
